// Command gen-docs writes one docs page per check module (CF-147), at
// docs/modules/<name>.md, from the two sources that already exist:
//
//   - docs/_data/modules.yml — id, human title and the answer-shaped summary
//   - docs/modules.md        — the prose section already written for each one
//
// Why split a 600-line page into 29: that page competes for one head term while
// the real traffic is long-tail ("checkfleet kafka consumer lag check", "check
// hls live edge cli"), and a dedicated page wins those without competing with
// anything. The combined page stays as the index.
//
// Nothing is rewritten by hand here — the prose has one home, and these pages
// are a projection of it. CI regenerates and fails on a diff (same gate as the
// skill references).
//
//	go run ./cmd/gen-docs           # write the pages
//	go run ./cmd/gen-docs -check    # fail if they are stale
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type module struct {
	Name    string `yaml:"name"`
	Title   string `yaml:"title"`
	Summary string `yaml:"summary"`
}

const genNote = "<!-- GENERATED by cmd/gen-docs from docs/_data/modules.yml and docs/modules.md. Do not edit by hand. -->"

// sectionRe matches a per-module heading in docs/modules.md, e.g.
// "## `certs` — TLS certificates {#certs}".
var sectionRe = regexp.MustCompile("(?m)^## `([a-z0-9]+)` — (.+?)(?: \\{#[a-z0-9]+\\})?$")

func main() {
	dataPath := flag.String("data", "docs/_data/modules.yml", "module index")
	srcPath := flag.String("src", "docs/modules.md", "combined modules reference")
	outDir := flag.String("dir", "docs/modules", "output directory")
	check := flag.Bool("check", false, "exit non-zero if the pages on disk are stale")
	flag.Parse()

	mods, err := readModules(*dataPath)
	if err != nil {
		fail(err)
	}
	prose, err := readSections(*srcPath)
	if err != nil {
		fail(err)
	}

	// A module in the index with no prose would silently ship an empty page.
	var missing []string
	for _, m := range mods {
		if strings.TrimSpace(prose[m.Name]) == "" {
			missing = append(missing, m.Name)
		}
	}
	if len(missing) > 0 {
		sort.Strings(missing)
		fail(fmt.Errorf("no section in %s for: %s — add the prose there, not here",
			*srcPath, strings.Join(missing, ", ")))
	}

	stale := false
	for _, m := range mods {
		want := []byte(page(m, prose[m.Name]))
		path := filepath.Join(*outDir, m.Name+".md")
		if *check {
			got, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(got, want) {
				fmt.Fprintf(os.Stderr, "stale: %s — run `go run ./cmd/gen-docs`\n", path)
				stale = true
			}
			continue
		}
		if err := os.MkdirAll(*outDir, 0o755); err != nil {
			fail(err)
		}
		if err := os.WriteFile(path, want, 0o644); err != nil {
			fail(err)
		}
	}
	if stale {
		os.Exit(1)
	}
	if !*check {
		fmt.Printf("wrote %d module pages to %s\n", len(mods), *outDir)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen-docs:", err)
	os.Exit(1)
}

func readModules(path string) ([]module, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var mods []module
	if err := yaml.Unmarshal(raw, &mods); err != nil {
		return nil, err
	}
	if len(mods) == 0 {
		return nil, fmt.Errorf("%s lists no modules", path)
	}
	return mods, nil
}

// readSections splits the combined reference into per-module prose, keyed by
// module id. The body of a section runs to the next section heading.
func readSections(path string) (map[string]string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	text := string(raw)
	locs := sectionRe.FindAllStringSubmatchIndex(text, -1)
	out := make(map[string]string, len(locs))
	for i, loc := range locs {
		name := text[loc[2]:loc[3]]
		start := loc[1] // just after the heading line
		end := len(text)
		if i+1 < len(locs) {
			end = locs[i+1][0]
		}
		out[name] = strings.TrimSpace(text[start:end])
	}
	return out, nil
}

// page renders one module page. nav_exclude keeps 29 entries out of the
// sidebar: modules.md stays the way in, and these are the landing pages.
func page(m module, prose string) string {
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "title: %s check\n", m.Title)
	fmt.Fprintf(&b, "description: >-\n  %s\n", m.Summary)
	b.WriteString("nav_exclude: true\n")
	fmt.Fprintf(&b, "permalink: /modules/%s\n", m.Name)
	b.WriteString("---\n\n")
	b.WriteString(genNote + "\n\n")

	fmt.Fprintf(&b, "# `%s` — %s\n\n", m.Name, m.Title)
	fmt.Fprintf(&b, "%s\n\n", m.Summary)
	fmt.Fprintf(&b, "```bash\ncheckfleet check %s --config checkfleet.yml\n```\n\n", m.Name)
	fmt.Fprintf(&b, "%s\n\n", prose)
	b.WriteString("---\n\n")
	b.WriteString("See the [full module reference]({{ '/modules' | relative_url }}) for every check,\n")
	b.WriteString("or [configuration]({{ '/configuration' | relative_url }}) for the config keys.\n")
	return b.String()
}
