// Command gen-skill writes the reference files the checkfleet skill loads on
// demand (CF-150): skills/checkfleet/references/{modules,config-schema}.md.
//
// They are GENERATED, not hand-written, because the config schema is the part
// an assistant invents most, and a copy maintained by hand diverges at the
// first release — exactly what happened to the intro of docs/modules.md, which
// sat at 18 modules while the registry had 29.
//
// Sources of truth, both already used by the shipping binary:
//   - internal/registry — the module list (the same one `check` dispatches on)
//   - internal/moduledoc — the descriptions (the same ones `checkfleet explain`
//     and the SARIF rules print)
//
// Defaults are not read from comments: the generator loads a config that
// enables every module through engine.LoadBytes, which applies the real
// defaults, then reflects over the result. A default that changes in code
// therefore changes here without anyone remembering to.
//
// Deterministic: same input, byte-identical output. CI regenerates and fails on
// a non-empty diff (CF-152).
//
//	go run ./cmd/gen-skill            # write the files
//	go run ./cmd/gen-skill -check     # fail if they are stale
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/Allan-Nava/checkfleet/internal/engine"
	"github.com/Allan-Nava/checkfleet/internal/moduledoc"
	"github.com/Allan-Nava/checkfleet/internal/registry"
)

const docsFront = `---
title: Permissions
nav_order: 14
description: >-
  What each checkfleet module needs on the system it watches, and what it
  explicitly does not — derived from the queries and endpoints it issues.
---

`

const header = "<!-- GENERATED by cmd/gen-skill. Do not edit by hand: run `go run ./cmd/gen-skill`. -->\n\n"

func main() {
	dir := flag.String("dir", "skills/checkfleet/references", "output directory")
	docsPath := flag.String("docs", "docs/permissions.md", "docs-site page for the permissions reference")
	check := flag.Bool("check", false, "exit non-zero if the files on disk are stale")
	flag.Parse()

	files := map[string][]byte{
		"modules.md":       []byte(header + modulesDoc()),
		"config-schema.md": []byte(header + schemaDoc()),
		"permissions.md":   []byte(header + permissionsDoc()),
	}

	// The same content also lands on the docs site (CF-181): a security reviewer
	// reads a URL, not a file inside a skill bundle.
	page := []byte(docsFront + header + permissionsDoc())
	if *check {
		if got, err := os.ReadFile(*docsPath); err != nil || !bytes.Equal(got, page) {
			fmt.Fprintf(os.Stderr, "stale: %s — run `go run ./cmd/gen-skill`\n", *docsPath)
			os.Exit(1)
		}
	} else if err := os.WriteFile(*docsPath, page, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	stale := false
	for name, want := range files {
		path := filepath.Join(*dir, name)
		if *check {
			got, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(got, want) {
				fmt.Fprintf(os.Stderr, "stale: %s — run `go run ./cmd/gen-skill`\n", path)
				stale = true
			}
			continue
		}
		if err := os.MkdirAll(*dir, 0o755); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		if err := os.WriteFile(path, want, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		fmt.Println("wrote", path)
	}
	if stale {
		os.Exit(1)
	}
}

// fullConfig returns a config with every module enabled and defaults applied,
// so reflection below sees the real default values rather than Go zero values.
func fullConfig() *engine.Config {
	var b strings.Builder
	b.WriteString("checks:\n")
	for _, name := range moduleKeys() {
		b.WriteString("  " + name + ": {}\n")
	}
	cfg, err := engine.LoadBytes([]byte(b.String()))
	if err != nil {
		panic("gen-skill: loading the all-modules config failed: " + err.Error())
	}
	return cfg
}

// moduleKeys returns the yaml key of every module in registry order.
func moduleKeys() []string {
	return registry.All(&engine.Config{})
}

func modulesDoc() string {
	var b strings.Builder
	b.WriteString("# checkfleet modules\n\n")
	b.WriteString("Every check module, what it detects, and the config key that enables it.\n")
	b.WriteString("Statuses are `OK`, `WARN`, `BAD` (target unhealthy) and `ERROR` (the check\n")
	b.WriteString("could not measure — a statement about the probe, not the target).\n\n")
	b.WriteString("Run one with `checkfleet check <name> --config checkfleet.yml`.\n\n")

	names := moduleKeys()
	sorted := append([]string(nil), names...)
	sort.Strings(sorted)
	for _, name := range sorted {
		doc, ok := moduledoc.Doc(name)
		if !ok {
			doc = "_(undocumented — add it to internal/moduledoc)_"
		}
		fmt.Fprintf(&b, "## %s\n\n%s\n\n", name, doc)
	}
	fmt.Fprintf(&b, "---\n\n%d modules.\n", len(sorted))
	return b.String()
}

// permissionsDoc renders the least-privilege reference (CF-181) from
// internal/moduledoc, the same source `checkfleet explain` and the SARIF rules
// read. Generated rather than written because a hand-kept copy drifts the first
// time a module gains a query — and a stale permissions document is worse than
// none: it is wrong with authority.
func permissionsDoc() string {
	var b strings.Builder
	b.WriteString("# checkfleet permissions\n\n")
	b.WriteString("What each check needs on the system it watches, and what it does **not**.\n")
	b.WriteString("Derived from the queries and endpoints the modules actually issue.\n\n")
	b.WriteString("`checkfleet perms --config checkfleet.yml` prints the subset below for the\n")
	b.WriteString("modules you actually run, in text, markdown or JSON — send that to whoever\n")
	b.WriteString("owns the system instead of this whole page.\n\n")
	b.WriteString("Every module is read-only: no check writes to the system it inspects.\n")
	b.WriteString("Credentials always come from the environment (`*_env`, `${VAR}`), never\n")
	b.WriteString("from the config file.\n\n")

	names := moduleKeys()
	sorted := append([]string(nil), names...)
	sort.Strings(sorted)

	var free, auth []string
	for _, n := range sorted {
		if p, ok := moduledoc.Perms(n); ok && p.Unauthenticated {
			free = append(free, n)
			continue
		}
		auth = append(auth, n)
	}

	fmt.Fprintf(&b, "## Needs no credential (%d)\n\n", len(free))
	b.WriteString("These reach the target over the network and read what it already exposes.\n\n")
	for _, n := range free {
		writePerm(&b, n)
	}
	fmt.Fprintf(&b, "## Needs an account (%d)\n\n", len(auth))
	for _, n := range auth {
		writePerm(&b, n)
	}
	return b.String()
}

func writePerm(b *strings.Builder, name string) {
	p, ok := moduledoc.Perms(name)
	if !ok {
		fmt.Fprintf(b, "### %s\n\n_(no permissions entry — add one to internal/moduledoc)_\n\n", name)
		return
	}
	fmt.Fprintf(b, "### %s\n\n%s\n\n", name, p.Summary)
	if len(p.Statements) > 0 {
		b.WriteString("```\n")
		for _, s := range p.Statements {
			b.WriteString(s + "\n")
		}
		b.WriteString("```\n\n")
	}
	fmt.Fprintf(b, "**Not needed:** %s\n\n", p.NotNeeded)
	if p.NeedsJudgement {
		b.WriteString("> The exact policy depends on how the target is deployed, so treat the\n")
		b.WriteString("> above as guidance rather than a recipe.\n\n")
	}
}

func schemaDoc() string {
	cfg := fullConfig()
	var b strings.Builder
	b.WriteString("# checkfleet config schema\n\n")
	b.WriteString("Keys of `checkfleet.yml`, with Go type and the default applied when the key\n")
	b.WriteString("is absent. A blank default means the zero value (`0`, `\"\"`, empty list).\n\n")
	b.WriteString("**Secrets never go in this file.** Use `${VAR}` interpolation, or the\n")
	b.WriteString("`*_env` keys that name an environment variable holding the credential.\n\n")

	b.WriteString("## Top level\n\n")
	writeFields(&b, reflect.ValueOf(*cfg), map[string]bool{"checks": true})

	b.WriteString("\n## Per module (under `checks:`)\n\n")
	checks := reflect.ValueOf(cfg.Checks)
	t := checks.Type()
	type mod struct {
		key string
		val reflect.Value
	}
	var mods []mod
	for i := 0; i < t.NumField(); i++ {
		key := yamlKey(t.Field(i))
		if key == "" {
			continue
		}
		mods = append(mods, mod{key, checks.Field(i)})
	}
	sort.Slice(mods, func(i, j int) bool { return mods[i].key < mods[j].key })
	nested := map[string]reflect.Type{}
	for _, m := range mods {
		v := m.val
		if v.Kind() == reflect.Pointer {
			if v.IsNil() {
				continue
			}
			v = v.Elem()
		}
		fmt.Fprintf(&b, "### `checks.%s`\n\n", m.key)
		writeFields(&b, v, nil)
		collectStructs(v.Type(), nested)
		b.WriteString("\n")
	}

	// The named struct types above (targets, mostly) are where an assistant
	// invents field names, so expand each one instead of leaving `CertsTarget`
	// as an opaque token.
	if len(nested) > 0 {
		b.WriteString("## Referenced types\n\n")
		names := make([]string, 0, len(nested))
		for n := range nested {
			names = append(names, n)
		}
		sort.Strings(names)
		for _, n := range names {
			fmt.Fprintf(&b, "### `%s`\n\n", n)
			writeFields(&b, reflect.New(nested[n]).Elem(), nil)
			b.WriteString("\n")
		}
	}
	return b.String()
}

// collectStructs records every named struct type reachable from t through its
// yaml-tagged fields, so each can be expanded once.
func collectStructs(t reflect.Type, out map[string]reflect.Type) {
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if yamlKey(f) == "" {
			continue
		}
		ft := f.Type
		for ft.Kind() == reflect.Pointer || ft.Kind() == reflect.Slice || ft.Kind() == reflect.Map {
			ft = ft.Elem()
		}
		if ft.Kind() != reflect.Struct || ft.Name() == "" {
			continue
		}
		if _, seen := out[ft.Name()]; seen {
			continue
		}
		out[ft.Name()] = ft
		collectStructs(ft, out)
	}
}

// writeFields emits one table row per yaml-tagged field of a struct value.
func writeFields(b *strings.Builder, v reflect.Value, skip map[string]bool) {
	t := v.Type()
	rows := make([]string, 0, t.NumField())
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if isInline(f) && f.Type.Kind() == reflect.Struct {
			rows = append(rows, inlineRows(v.Field(i))...)
			continue
		}
		key := yamlKey(f)
		if key == "" || skip[key] {
			continue
		}
		rows = append(rows, fmt.Sprintf("| `%s` | %s | %s |", key, typeName(f.Type), defaultOf(v.Field(i))))
	}
	if len(rows) == 0 {
		b.WriteString("_No keys._\n")
		return
	}
	b.WriteString("| Key | Type | Default |\n|---|---|---|\n")
	b.WriteString(strings.Join(rows, "\n"))
	b.WriteString("\n")
}

// inlineRows renders an inlined struct's fields as if they were the parent's.
func inlineRows(v reflect.Value) []string {
	t := v.Type()
	var rows []string
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		key := yamlKey(f)
		if key == "" {
			continue
		}
		rows = append(rows, fmt.Sprintf("| `%s` | %s | %s |", key, typeName(f.Type), defaultOf(v.Field(i))))
	}
	return rows
}

func yamlKey(f reflect.StructField) string {
	tag := f.Tag.Get("yaml")
	if tag == "" || tag == "-" {
		return ""
	}
	return strings.Split(tag, ",")[0]
}

// isInline reports whether a field is spliced into its parent's key space
// (`yaml:",inline"`). Its own name is not a key, so writeFields must descend
// into it — skipping it silently is how client_cert/client_key/ca_cert first
// landed undocumented, which is the exact failure this reference exists to stop.
func isInline(f reflect.StructField) bool {
	for _, opt := range strings.Split(f.Tag.Get("yaml"), ",")[1:] {
		if opt == "inline" {
			return true
		}
	}
	return false
}

// typeName renders a Go type the way a config author thinks about it.
func typeName(t reflect.Type) string {
	switch t.Kind() {
	case reflect.Pointer:
		return typeName(t.Elem())
	case reflect.Slice:
		return "list of " + typeName(t.Elem())
	case reflect.Map:
		return "map of " + typeName(t.Elem())
	case reflect.Struct:
		return "`" + t.Name() + "`"
	default:
		return "`" + t.Kind().String() + "`"
	}
}

// defaultOf renders a field's post-defaults value, or "" for a zero value.
func defaultOf(v reflect.Value) string {
	if !v.IsValid() || v.IsZero() {
		return ""
	}
	switch v.Kind() {
	case reflect.Pointer, reflect.Slice, reflect.Map, reflect.Struct, reflect.Interface:
		return ""
	case reflect.String:
		return "`" + v.String() + "`"
	default:
		return fmt.Sprintf("`%v`", v.Interface())
	}
}
