package scaffold

import (
	"strings"
	"testing"

	"github.com/Allan-Nava/checkfleet/internal/engine"
	"github.com/Allan-Nava/checkfleet/internal/registry"
)

// Every supported module's snippet must produce a config that loads and
// validates with no problems — the generated file is usable as-is.
func TestEverySnippetLoadsAndValidates(t *testing.T) {
	for _, m := range Supported() {
		t.Run(m, func(t *testing.T) {
			out, err := Config([]string{m})
			if err != nil {
				t.Fatalf("Config(%q): %v", m, err)
			}
			cfg, err := engine.LoadBytes([]byte(out))
			if err != nil {
				t.Fatalf("generated config for %q does not parse: %v\n%s", m, err, out)
			}
			if problems := engine.Validate(cfg); len(problems) != 0 {
				t.Errorf("generated config for %q has problems: %v\n%s", m, problems, out)
			}
		})
	}
}

func TestDefaultModules(t *testing.T) {
	out, err := Config(nil)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "certs:") || !strings.Contains(out, "http:") {
		t.Errorf("default config should contain certs + http:\n%s", out)
	}
	if !strings.Contains(out, "generated by") {
		t.Error("generated file should carry a header comment")
	}
}

func TestMultipleModulesDeduped(t *testing.T) {
	out, err := Config([]string{"http", "certs", "http"})
	if err != nil {
		t.Fatal(err)
	}
	if n := strings.Count(out, "\n  http:"); n != 1 {
		t.Errorf("http should appear once, got %d\n%s", n, out)
	}
	// Order preserved: http before certs.
	if strings.Index(out, "  http:") > strings.Index(out, "  certs:") {
		t.Error("module order should follow the caller (http before certs)")
	}
}

func TestUnknownModuleErrors(t *testing.T) {
	if _, err := Config([]string{"http", "bogus"}); err == nil {
		t.Error("unknown module should error")
	}
}

func TestSupportedCoversRegistry(t *testing.T) {
	// Guard against a module being added without an init snippet.
	for _, m := range registry.All(&engine.Config{}) {
		if _, ok := snippets[m]; !ok {
			t.Errorf("module %q has no init snippet (add one to scaffold.go)", m)
		}
	}
}
